### ISSUE TITLE
Feature Request: Make export format a bibliography style

### ISSUE THREAD

**Issue by mincowski** [ZotPlus/zotero-better-bibtex#128]
## Idea

The feature to export a list of citation keys using the `LaTeX Citation` translator works great. However, I frequently want to send information about a paper to someone and it would be great to have a quick way of copying bibliographic information in a human readable format (e.g. one of the default styles like the Chicago one) as well.

## How it could work

If the `LaTeX Citation` translator could be converted to a Zotero style, one would have two options: copy the citation or the bibliography. Copying the citation could give the citation key whereas the bibliography could give e.g:
```
Crick, Francis. “Central Dogma of Molecular Biology.” Nature 227, no. 5258 (August 8, 1970): 561–63. doi:10.1038/227561a0.
```
This would give users two convenient shortcuts (`Ctrl + Shift + A` and `Ctrl + Shift + C`) to access both features.

Or is there a way to achieve something similar using translators? To me, the [Zotero documentation](https://www.zotero.org/support/dev/translators) suggests that this requires a style instead of a translator.

**Comment by AllThatIsTheCase** [comment]
It's a little more complicated than adding a new style. It would require adding a formatter, not a style; writing a formatter is not prohibitively complicated (BBT includes a Markdown formatter, for example), but hooking into the UI is nigh impossible because of the way Zotero implements it. The closest I could come to hooking into the UI is to replace the RTF or HTML export under the covers.

What you want, however, seems doable with the way things are. The LaTeX citation translator isn't really meant to use as an exporter, but to set it as a quick-export, to be used as either drag-and-drop, or to copy to the clipboard using ctrl-shift-c. To copy the bibliography you show above to the clipboard can be done by right-clicking the desired items, selecting "Create bibliography", "Copy to Clipboard", "OK".

**Comment by AllThatIsTheCase** [comment]
To configure the quick-export, see https://zotplus.github.io/better-bibtex/Citation-Keys.html, under "Drag and drop/hotkey citations"

**Comment by mincowski** [comment]
Thank you for the explanations. Since it is not as basic as I thought, I'll close the issue.
I was well aware of the right-click method you mentioned but was hoping that this could be solved more conveniently.
Thank you for your quick reply!

**Comment by AllThatIsTheCase** [comment]
The right-click thingy has a shortcut, I think the default (but configurable) shortcut is Ctrl-Alt-A
