### ISSUE TITLE
Zotfile-like rename PDF using bibkey

### ISSUE THREAD

**Issue by rcoreilly** [ZotPlus/zotero-better-bibtex#189]
we like to keep our PDF's named the same as the bibkey, for easy management etc (probably not strictly necessary in zotero but does make things future proof for any subsequent system that one might want to migrate to, and just for plain OCD), and it doesn't look quite possible to replicate our [authors3][shortyear] bibkey format on zotfile unfortunately.  How hard would it be to just grab some code from zotfile and modify it to use the bibkey stored in the extra field for the "Rename PDF from meta data" function?  I bet there would be more than just my lab that would use this feature :)

**Comment by retorquere** [comment]
Could you try the version at http://is.gd/cghIbe ? When both that and zotfile are installed, you should be able to use `%b% in the zotfile renaming patterns to get the bibtex key.

**Comment by lucisandor** [comment]
Zotfile does all sorts of automatic renaming. They are not as fast paced though, so I wouldn't hold my breath to get them use bibtex keys. But you might be able to use its predefined % functions to recreate the bibtex key in Zotfile settings. It depends on how complex your keys are.

**Comment by retorquere** [comment]
If you install the version I uploaded to http://is.gd/cghIbe (as a test -- if it works well I'll release it) it will patch zotfile on-the-fly to add supoort for the %b parameter. zotfile will work as it usually does, except that %b will map to the item's BBT key.

**Comment by rcoreilly** [comment]
That new version with %b% doesn't seem to work for me.  I did actually manage to find someone's regex to get the two-digit year, so I was able to get it to work with our key, BUT if there are a,b etc suffixes for conflicts then this definitely wouldn't work.  So the %b would be better and a lot easier.

Also, this version does fix the 187 bug with keep updated on groups, but the performance is so slow still that it is not usable at this point for 21K refs.  Did this version have the new caching function?  Thanks!

**Comment by retorquere** [comment]
Damn. I'll have to look further for the zotfile integration.

Yes, this version does have the caching updates. Exports after the first should be about 10x faster because the cache will be filled.

I've done some profiling; the bulk of the time is spent in Zotero getting the items ready for export, and it looks like there's very little I can do about that. 21k items is going to be slow with even the most nimble of exporters, like Zotero TestCase, which just dumps what Zotero hands the translators as-is, or indeed BBT with a primed cache. I'll have a peek if I can short-circuit Zotero to skip prep for cached items, but that's going to be invasive, and thus tricky. If you're interested in being kept abreast of this, please file a separate issue -- this one is for the zotfile integration.

**Comment by rcoreilly** [comment]
Did your patch to zotfile just write to the about:config extensions.zotfile.wildcards.user setting?  perhaps because I had already added this short year regex there it didn't work?  will file a new bug ticket for caching.

**Comment by retorquere** [comment]
The change patches the zotfile code at runtime (also known as monkey-patching) to add the feature. I haven't touched any of zotfile's settings.

**Comment by retorquere** [comment]
Tests are running, .31 will be out in a few minutes. The key is still `%b`

**Comment by retorquere** [comment]
Note that this still requires zotfile to be installed. This patch integrates BBT with zotfile, it doesn't replace it.

**Comment by rcoreilly** [comment]
works perfectly -- thanks so much -- our desired zotero functionality is now complete!

**Comment by retorquere** [comment]
It is my pleasure.
