### ISSUE TITLE
Database schema upgrade error

### ISSUE THREAD

**Issue by madhusudansingh** [ZotPlus/zotero-better-bibtex#208]
Please see report: http://is.gd/LScmdh

**Comment by retorquere** [comment]
Could you do the following for me:

1. Go into preferences-> advanced, go to the "Files and Folders" tab, and click "Show Data Directory". The finder will open, you will see files "betterbibtex.sqlite" and "betterbibtex.sqlite-journal"
2. Close Firefox. The file "betterbibtex.sqlite-journal" will disappear.
3. Drop the file "betterbibtex.sqlite" into https://dbinbox.com/allthatisthecase

**Comment by retorquere** [comment]
Sorry, that should be https://dbinbox.com/retorquere

**Comment by madhusudansingh** [comment]
I don't use Firefox. Just standalone on Mac OSX.

Let me know what you need.

**Comment by retorquere** [comment]
Ah, OK. Same procedure, just with standalone.

**Comment by madhusudansingh** [comment]
Done!

**Comment by retorquere** [comment]
Test are running, 0.11.4 will be released when they pass.

**Comment by retorquere** [comment]
And apologies for the disruption.

**Comment by madhusudansingh** [comment]
No worries.

Thanks for making Zotero BibTeX so much better.

Is there a plan in the works to set the default to the following conditions:

1. All keys, once generated, are fixed. (This is what a vast (if not
everyone) majority of people would want). Currently, the pin preferences
are hidden.
2. Set default key format to author_lastname:year:x, where x=1,2,3,4.
3. Make the key visible in the right pane in Zotero (this is what Mendeley
does - and it is a huge time saver).
4. Auto-update a user-defined file (don't base it off a given export - just
do it more logically - user specifies the file against which the database
is sync'ed.).

Of course, users should be able to change this, but I can tell you the
above are the defaults that nearly everyone wants (have about 16 years of
experience with LaTeX and have worked with a very large number of
collaborators).

Thanks once again!

**Comment by retorquere** [comment]
> 1. All keys, once generated, are fixed. (This is what a vast (if not everyone) majority of people would want). Currently, the pin preferences are hidden.

By hidden, you mean buried in the myriad of options BBT offers? :). Yeah, they're not too prominent. This would be doable (and is in fact one of the preferences: `Better BibTeX - Citation - Auto-pin: on item change`. The problem in making this the default is that it actually changes the `extra` field of the reference, as there is currently no other way to have these keys sync that doesn't upset the Zotero devs, and I'm not too keen on modifying references without explicit consent from the user. Also, each change marks the reference for sync, and the current sync infrastructure of Zotero is not equipped to handle large amounts of changes in one go; enabling this by default would mean everyone's entire library would sync to the Zotero servers, and bad stuff happens if this times out. Not my preference, but until the new sync infra they;re working on is online, it is what I have to work with.

The default is to "soft-pin"; as long as nothing changes in a reference that is used in your citation key formatter, the key ought not to change. So if you have `[auth][year]`, and you change the title, the key shouldn't be affected.

> 2. Set default key format to author_lastname:year:x, where x=1,2,3,4.

This seems to me a personal, not a universal preference. No accounting for taste.

> 3. Make the key visible in the right pane in Zotero (this is what Mendeley does - and it is a huge time saver).

That's on my to-do list, but you can have it show up in the reference list in the interim by enabling the `extra` column, and enabling `Show cite key instead of extra` in the BBT preferences.

> 4. Auto-update a user-defined file (don't base it off a given export - just do it more logically - user specifies the file against which the database is sync'ed.).

I don't understand -- what would this entail other than the existing auto-export?

> Of course, users should be able to change this, but I can tell you the
above are the defaults that nearly everyone wants (have about 16 years of
experience with LaTeX and have worked with a very large number of
collaborators).

You wouldn't believe the amount of variability I've seen over time with regards to preferences here :). One thing I'm still considering is to have per-group syncable settings, but the UI work for this is off-putting, and it requires circumventing a whole heap of stuff in Zotero to get it to work, which is fragile. With a guaranteed-to-break-all-plugins Zotero 5.0 slated, I'm deferring all fragile stuff until that has dropped.

But please do feel free to lodge feature-request issues for these. I have terrible memory, so I rely on these sitting in the issues list for when sudden inspiration hits me for a clean fix.

**Comment by retorquere** [comment]
Showing the citation key in the item pane itself is more involved than showing it in the overview (as tricky as that was), as the item pane uses one of the more esoteric features of Firefox to work, and one that is sort of actively hostile to the regular mechanisms of extending the UI in Firefox (standalone is built on xulrunner, which is simply Firefox stripped to its bare essentials, so the same problem exists there).

**Comment by retorquere** [comment]
(meh, involved equals challenge. tests are running)

**Comment by retorquere** [comment]
new release has citekey display.

**Comment by madhusudansingh** [comment]
Thanks!

The cite key display works beautifully. I just ran generate bibtex key for
all the publications in my new Zotero collection (~ 1000) and it did not
appreciably hang. Took a minute, but I got all the keys done.

However, the export library is still not working (same error as before).
Shall I enable debugging, and restart Zotero to get you a full trace?

**Comment by retorquere** [comment]
That would be much appreciated.

**Comment by madhusudansingh** [comment]
Done.

Don't know if you need a new tracker for this, but I got:
http://is.gd/nW09lq

**Comment by retorquere** [comment]
.7 is now out, should take care of that.

**Comment by dmbortz** [comment]
I don't know if I'm having the same issue as in this thread, but I am now also get an error when trying to export a library using this plugin.  I'm using version 0.11.8 of the plugin.

Do you want me to upload an sqlite file?

**Comment by retorquere** [comment]
@dmbortz `Report ZotPlus Error` will suffice. Could you please open a separate issue?

**Comment by retorquere** [comment]
@madhusudansingh if the original issue is fixed for you, can you close this issue? Thanks.

**Comment by madhusudansingh** [comment]
The issue is not fixed :(

Still get that JavaScript error upon trying to export library. I did
restart Zotero before testing this, so Better BibTeX should have updated.

**Comment by retorquere** [comment]
Ok, can you generate a new debug log?

**Comment by retorquere** [comment]
Hold on, a restart doesn't automatically update extensions. You need to go into the addins screen and have it check for updates.

**Comment by retorquere** [comment]
I'd really appreciate feedback on this issue. Are you sure you are currently on 0.11.11, and can you generate a new debug log if you are?

**Comment by madhusudansingh** [comment]
Sorry, I was busy with something and didn't check my email.

You were right - the version did not update with a Zotero restart. I was
stuck at 0.11.6. Its updated now, and working like a charm.

Thanks!!

**Comment by retorquere** [comment]
Glad it's working for you. Could you still elaborate on

> Auto-update a user-defined file (don't base it off a given export - just do it more logically - user specifies the file against which the database is sync'ed.).

**Comment by madhusudansingh** [comment]
It's not that big a deal. It's just that the current method of auto update
relies on you going to a different screen, enabling an easily missable
option, and then it works.

Instead, there should be a field to enter a file name which Zotero would
sync to, automatically by default, with an extra radio button allowing a
person to opt out of auto sync to bibtex.

That would make it simpler, mirror the most common case of use, and not
have this untidy method of having to leave preferences to set it up.

**Comment by retorquere** [comment]
I still don't understand, I'm sorry

> It's not that big a deal. It's just that the current method of auto update relies on you going to a different screen, enabling an easily missable option, and then it works.

But which option? What screen? And different from what? The default for auto export is "on idle", not "off". It's the only option I could think of that sort of matches your description, but "on idle" fits my description of "it just works".

> Instead, there should be a field to enter a file name which Zotero would sync to, automatically by default, with an extra radio button allowing a person to opt out of auto sync to bibtex.

But where should this field be? And if "sync to bibtex" would be disabled there, what would it do? 

> That would make it simpler, mirror the most common case of use, and not have this untidy method of having to leave preferences to set it up.

You hardly ever have to be in preferences for auto export. I never go there unless I made an error. You can see the existing auto exports in the preferences, and you can remove them there, but that's all you can do. I think I'm missing something important in your description, I'm always up to make the UI better, but I just honestly don't understand what your request is.

**Comment by madhusudansingh** [comment]
Right now, if I want to enable an export, I have to browse to the
preferences screen for the auto export (under better bibtex), that tells me
that I need to tick Keep updated when I go to do an export. This is messy.
I call it the export dance.

Just change the auto export preferences screen to accept a filename and the
rest of the controls (I would change the default to on change (and not on
idle) - but that is a minor point).

Don't tell the user what to do on that screen and force him to browse away.
Its unintuitive.

Look at how Mendeley. It does not do the export dance.

Am I making any headway in explaining myself?

**Comment by retorquere** [comment]
> Right now, if I want to enable an export, I have to browse to the preferences screen for the auto export (under better bibtex), that tells me that I need to tick Keep updated when I go to do an export. This is messy. I call it the export dance.

But that simply isn't required. Why do you go to the preferences for auto-export? Simply ticking "Keep updated" during export will do.

> Just change the auto export preferences screen to accept a filename and the rest of the controls (I would change the default to on change (and not on idle) - but that is a minor point).

You mean that in the preferences screen you could fill out a filename and have that set up a new auto-export? That would be very inconvenient, as you'd still have to select which library or collection you want to export. It's actually one step more than the current setup.

I have chosen "on idle" on purpose -- I don't want the default settings to have too much of a performance impact. Firefox (and therefore also Zotero, either standalone or the Firefox plugin) lock up the UI while doing an export. I don't want that to be the user experience unless the user chooses it.

> Don't tell the user what to do on that screen and force him to browse away. Its unintuitive.

The text is there for those who end up there by accident. It's not meant to be the primary experience. You make it sound like the user *has* to be there for every auto-export, and that simply isn't the case. Not even close. Mendeley makes you go to the preferences for auto-export, but that is not the case for Zotero+BBT.

> Look at how Mendeley. It does not do the export dance.

For starters, the dance you propose is entirely unnecessary. You want a collection updated automatically, you just select that collection, tick "Keep updated", and that's that. Secondary, the only option Mendele has is to bulk export to a single file (hardly useful), one-per-reference (even less useful), or one per collection, but layed out in a single directory structure that must directly mirror your collection layout. There is no dance, because there are no options (I don't consider the first two serious options).

**Comment by retorquere** [comment]
I think I now do understand what you were explaining, so thanks for sticking with it until I got it, but I respectfully disagree. When you say that

> Instead, there should be a field to enter a file name which Zotero would sync to, automatically by default, with an extra radio button allowing a person to opt out of auto sync to bibtex.

What would be the purpose of filling out a filename and then disabling sync? The only purpose for the filename being present could be sync, and then specifically bibtex sync, because my auto-export facility doesn't universally work with all Zotero translators. It could perhaps, but it doesn't, because it requires changes in the translators that want to use it. The BBT translators are heavily instrumented for caching to make background export possible -- any other translator would grind Zotero to a halt when exporting even a modest 100 entry file. With the BBT translators, 100 entries is unnoticable. In fact I have export set to "on change" myself. I know of others doing crazy auto-exports of 22k references, which takes under a minute with BBT, but would take anywhere between 5 to 15 minutes with any other translator. So that file-field could really only have one sensible use, and that is to auto-export using BBT.

> That would make it simpler

OK, we agree on this, but it would make it simpler by reducing all choice to a single option, and that option doesn't match my own use-case. I collaborate with others on articles and these files sometimes live in Dropbox, sometimes in Owncloud, sometimes in Google drive... to allow for that in Mendeley you'd have to set up a forest of symlinks, which is not simpler.

> mirror the most common case of use,

Only if you're using auto-export to keep a backup of your full library, but that is not the case of use I have in mind. For backup, I think a script that downloads your library straight from the Zotero server is vastly superior. The most common case of use I have in mind is paper-specific bib files. If I submit for publishing, I don't generally want to submit a 2000+ entry bibfile, just those that belong to that paper. I would venture to guess that that is a common enough use case, and the feedback I've been getting seems to validate that belief.

> and not have this untidy method of having to leave preferences to set it up.

But this method is only yours. I hardly ever go into the prefs now that they're set up to my liking, certainly not to set up auto-export. For auto-export, I select a collection, Export, select "Keep updated", done. There's no trip to the preferences involved. I don't even understand why you wound up there, other than possibly curiosity. There's nothing you can do there except remove exports you no longer want to have running, and even that is hardly necessary, because if you re-export to the same file, it gets silently overwritten. There's no need to remove it in the prefs to set up a new sync if that's the reason you went to the prefs. In the case that seems to have your preference, a single file that exports your whole library, would not require *any* trip to the prefs. You just set it up once and done.

**Comment by retorquere** [comment]
You might find http://rokdd.de/b/zotero-autoexport interesting -- I think it does exactly what you want. I haven't tested it beyond installing it, but it looks very much like the Mendeley interface.

**Comment by retorquere** [comment]
And it should work with the BBT exporters -- I see no reason why they should conflict.
