### ISSUE TITLE
Citation Key not produced

### ISSUE THREAD

**Issue by lizzydoodle** [ZotPlus/zotero-better-bibtex#252]
When using Blog Post (or a number of other Item Types, have not tried them all), the citation key is not produced correctly. Usually it only takes the author with _ before it, but once I have added the author/date information, it does not get updated. Deleting the information in the Extra line does not work either (in fact, I only see that bibtex: _title_ entry in some Item Types produced at all.

**Comment by retorquere** [comment]
There's no indication of an error in the logs you submitted unfortunately. Can you right-click on one of the entries that doesn't do what it's supposed to on export, and click "report zotplus error" from that menu? That will give me the reference in question, perhaps I can reproduce the problem from the sample.

**Comment by lizzydoodle** [comment]
Report IDs: 
4HG9RZVX-C2R8JK9N
K2PVNKNJ-JQ4K2WEM
I3JG5H3G-896SC4PT
I use the standard in the Preferences > Better BibTeX dialog:
[auth:fold:lower]_[Title:fold:nopunct:skipwords:select,1,1:lower]_[year][0]

**Comment by retorquere** [comment]
These entries contain a fixed cite key in the `extra` field; once that's there, BBT will not change it. I think I know how it might have gotten there, can you tell me whether this diagnosis plausibly describes your situation?

1. You have BBT auto-pin set to "on change"
2. You have imported the above references into Zotero, but they were incomplete as they were imported
3. You have augmented the references to add the missing data
4. The citation key does not reflect this.

If this is a correct description of your situation, then what happened is that at step 2, the reference was technically "changed" (as a creation counts as a change), the citation key got fixed at that moment using the incomplete data, and after that, BBT respects the fixed cite key and does't change it anymore.

If this is, again, correct (and I'm just guessing it is), you can fix this by either:

1. disabling auto-pinning on change, or
2. right-clicking the entries you want to see updated and re-pinned and selecting "Generate BibTeX key"

**Comment by lizzydoodle** [comment]
Thanks for the super fast help and assistance! When I turned on extended De-bug and restarted FF (as it says in the description) and tried to recreate the problem - it was solved. You describe the steps exactly right. What happened was that usually I delete the incorrect entry under "Extra:", say "bibtex: _theory_" after I have added the missing information and then the BibTeX key gets generated as it should. The problem was, there was no entry under "Extra:" sometimes. When I restarted, they were present in all the Item Types where they had been missing before (thus I couldn't recreate the problem). 

I also tried your 2. suggestion (right-clicking and generating BibTeX key manually) but that wouldn't work - that's why I posted this initially.
Glad it's working now. Probably should just restart the browser in such cases? Happens quite frequently when BBT is updated.

**Comment by retorquere** [comment]
I appreciate your appreciation :) 

I'm loathe to recommend "just restart your browser" other than a pragmatic measure. I don't want BBT to have bugs that require this. If manual key generation doesn't work for you, that's a bug I'd love to fix.

I do realize BBT is a little volatile; my time however is stretched between a full time job, a study, and a family, so I haven't been able to prevent errors getting out in the wild. I do have a fairly substantial test suite at this time, and I generally add new test cases for each bug I solve to prevent regression, but it's an imperfect process. I try to make up for the imperfection by having good turnaround times.

I would kindly request though that if that is indeed the case, it be filed as a separate issue. Whether the current issue is sufficiently dealt with I would want to leave up to you -- if there are more questions or remarks relating to the issue as described, I welcome them, but if not, I generally prefer the user rather than me to close issues when they are themselves satisfied that it should be.

**Comment by lizzydoodle** [comment]
Again - THANK YOU! Would be totally lost in my workflow without BBT!

**Comment by retorquere** [comment]
It is my sincere pleasure.
