### ISSUE TITLE
"Generate / Clear BibTex key" should not change "modified" date

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-better-bibtex#273]
I accidentally (and stupidly) selected "Generate BibTeX key" after having selected *all* my items. (I wanted to generate a report to see duplicates…).

I think there should be a Confirmation dialog for "Generate BibTeX key" and "Clear BibTeX key" options, at least when a certain numbers of items are concerned, e.g. more than 10 items are selected.

In my case, there's no damage (except that all my items have now a similar "Date modified" and that's a sufficient reason for me to revert my database with a backup) but I assume that it could be more annoying if one has customized its keys.

Thanks!

**Comment by retorquere** [comment]
It really just shouldn't change the date to begin with. I'll cut a release when the tests run green

**Comment by gracile-fr** [comment]
I thought that changing the date was necessary for syncing purpose. That's not the case ?
Did you close this issue because the feature request – adding a confirmation dialog before generating or clearing more than 10 keys – isn't a good idea?

**Comment by retorquere** [comment]
Zotero has two timestamps per reference, one to signify "last changed", the
other to signify "last synced". Saving an item changes both by default, but
an extension can request either one to remain untouched, which I've done
now for "last changed".

I closed the issue because I had assumed the current solution seemed to
address your initial problem statement, if not by using the proposed
solution. I hadn't understood this was your preferred option. Is it?

**Comment by gracile-fr** [comment]
If one has set its own fixed keys and accidentally click Clear, they're lost. Not a big deal if a limited amount of items are concerned, but if it's a whole library…

**Comment by retorquere** [comment]
Fair enough; I've added it now. It's not that I didn't like your solution, but unless something is specifically listed as a desideratum, my thought process for adding stuff to BBT goes a little like:

* Yeah, I need to do that
* But stuff that pops up is distracting
* Anything that could pop up needs to have adjustable behavior so as to minimize annoyance
* Adjustable behavior adds to the xmas tree that is the BBT prefs pane
* I don't really like UI work (that really should have been the top reason listed, but this order makes me look better), and since I'm also not very good at UI work, it is an act of kindness not to expose people to my attempts at it.

**Comment by retorquere** [comment]
1.2.1 includes this change.

**Comment by gracile-fr** [comment]
Thanks ! I understand your reluctance towards UI work. In this case, this is that release which is an act of kindness.

**Comment by retorquere** [comment]
BTW to minimize interaction it'll only trigger the warning if you're actually making a change that passes the threshold (currently arbitrarily but changeably set at 10); setting new keys always counts as a change, but clearing already non-pinned keys doesn't count.

**Comment by retorquere** [comment]
(so if you have 100 references selected but only 5 of them have a pinned key, clearing them won't pop up a warning, setting them will).
