### ISSUE TITLE
Smarter way to export CSL date override

### ISSUE THREAD

**Issue by retorquere** [ZotPlus/zotero-better-bibtex#352]
- for biblatex: Test whether string in `{:issued: …}`, `{:accessed: …}` etc. matches a biblatex (=EDTF Level 0) date or date range. (Biblatex manual: “The date fields … require a date specification in yyyy-mm-dd format. Date ranges are given as yyyy-mm-dd/yyyy-mm-dd. Partial dates are valid provided that date components are omitted at the end only. You may specify an open ended date range by giving the range separator and omitting the end date (e. g., yyyy/).”) When matching, export to the biblatex `date` field; if not, export to the biblatex `year` field (which, unlike `date`, can be used for literal/free-form date strings).
- for “Pandoc JSON”: Same test. When matching, reformat date or date range according to CSL specs, e.g., `{ "issued": { "date-parts": [ [ 2014, 12, 31 ], [ 2015, 01, 01 ] ] } }`; if not, export to a “literal” element, e.g., `{ "issued": { "literal": "13th century" } }`. See [citeproc-js specs](http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#dates).

**Comment by retorquere** [comment]
For Pandoc JSON I simply export the CSL-JSON that Zotero generates, with the added change that the fields extracted from the 'extra' field are set on the generated JSON. I should perhaps just not do that for the CSL-style fields; that is perhaps better handled by the CSL processor itself.

**Comment by nickbart1980** [comment]
> … that is perhaps better handled by the CSL processor itself.

No, since pandoc can only deal with CSL JSON that strictly follows the specs; it neither understands the ad hoc `{:blah: blah}` elements in “Extra”, nor `"issued": "2014-12-31/2015-01-01"`. It’d have to be `{ "issued": { "date-parts": [ [ 2014, 12, 31 ], [ 2015, 01, 01 ] ] } }` and `{ "issued": { "literal": "13th century" } }`.

**Comment by retorquere** [comment]
@nickbart1980: I can find the part on the date field formatting, but not the part that says "otherwise, use the year field". The bibLaTeX manual says that "year" (and even "month") are legacy fallbacks to "date", implying the same rules go for those.

**Comment by retorquere** [comment]
WRT pandoc: alright, then I'll parse them out myself.

**Comment by retorquere** [comment]
BTW, I meant: the CSL engine inside Zotero already does this kind of thing (albeit not perfectly, see https://github.com/zotero/zotero/issues/845#issuecomment-141894703), but I can do the parsing myself as a workaround.

**Comment by nickbart1980** [comment]
Re: biblatex `date` vs. `year` fields: A well-kept secret … but just try it, literal stuff in the `date` field just won't work, but it does when in the `year` field. The biblatex-chicago manual is aware of this: “year – Standard biblatex field. It usually identifies the year of publication, though unlike the date field it allows non-numeric input, so you can put “n.d.” (or, to be language agnostic, \bibstring{nodate}) here if required, or indeed any other sort of non-numerical date information. If you can guess the date then you can include that guess in square brackets instead of, or after, the “n.d.” abbreviation.”

**Comment by retorquere** [comment]
I need to take into account #245; the Zotero date parser is quite enthusiastic in that it will do its darnedest  to get out a date of whatever has been put in. I don't want to demand people input dates in EDTF always, but I'd also like to acknowledge the difference between `[year/month]` (most likely literal) `year/month` and `date/date`. The latter two are ambiguous of course, and I haven't yet found a good heuristic/marker.

**Comment by retorquere** [comment]
(I mean `11/2012` is ambiguous between `november 2012` and a date range)

**Comment by retorquere** [comment]
Wait, the brackets is an official thing? Would `[1802]/[1833]` be a meaningful `year` value?

**Comment by nickbart1980** [comment]
> Would [1802]/[1833] be a meaningful year value?

No, not at all. In biblatex you should use `date` and `origdate`; in CSL `issued` and `original-date` – and let the style decide on formatting (brackets or whatever).

> (I mean 11/2012 is ambiguous between november 2012 and a date range)

That’s why I’m all for using EDTF Level 0 exclusively when dealing with dates in Zotero’s “Extra” field.

**Comment by retorquere** [comment]
Oh yeah sure in the extra field, but I'm also thinking about stuff entered in the regular date fields.

But `[1802]/[1833]` would be a date-range, right? Not an date/origdate.

**Comment by retorquere** [comment]
The brackets being an official thing would mean I could take out the configurable I put in place for #245.

**Comment by nickbart1980** [comment]
If I wanted to express a date range, i'd use `[1802/1833]`.

But the real problem is that Zotero's current date parsing is so weird. `[1802]/[1833]` in the Date field is parsed and exported as `1802`; `2014-12-31/2015-02-03` as `2014-12-31`.

My hope was that with `{:issued:2014-12-31/2015-02-03}` in the “Extra” field, BBT might be able to export a date range to CSL JSON so that it can be used with pandoc – but if I understand you correctly and BBT might also export Zotero's “Date” field in a more sensible manner (at least if it contains EDTF Level 0 dates and ranges) that'd be fantastic.

**Comment by nickbart1980** [comment]
> … the brackets is an official thing?

Ok, now I read https://github.com/ZotPlus/zotero-better-bibtex/issues/245, and I'd still say, no, brackets are never “official”, neiter in biblatex nor in a CSL context. However, if a user enters brackets, or anything else that does not match a well-defined date spec into a date field, the field content should be treated as a literal string, which is possible in both biblatex and CSL. Zotero’s parsing, of course, is clearly overzealous here, but if you have found a way of bypassing this and having BBT parse/export date fields more sensibly, that's great. 

Now, if BBT managed to export Zotero's "Date" field to CSL JSON as described earlier, `date-parts` if it's an EDTF Level 0 date or range, `literal` otherwise, we could even forget about dealing with `{:issued:}` in Zotero's "Extra" field altogether since that'd no longer be necessary.

**Comment by retorquere** [comment]
The EDTF date/ranges for the `date` field is easy, so I'm going to do that regardless. I'm pondering how to do it more generally, given the plethora of ways dates find their way into Zotero.

The Zotero date parser does its best. Can't fault them for that. The assumption behind it is that you entered a date, and it tries to find it.

**Comment by nickbart1980** [comment]
> The EDTF date/ranges for the date field is easy, so I'm going to do that regardless. 

Fantastic, looking forward.

**Comment by nickbart1980** [comment]
Some at Zotero have expressed a strong dislike of the `{:csl-variable: content}` format. They prefer a simpler, newline-separated `csl-variable: content` format for the ‘Extra’ field, so you might want to cater for both of these.

Examples:

~~~
Foo bar {:original-date: 1888-09-18} {:medium:DVD} baz
~~~
and
~~~
Foo bar
original-date: 1888-09-18
medium: DVD
baz
~~~

**Comment by retorquere** [comment]
This already works, no? Not all CSL vars are present, since I add them when I encounter them and understand their mapping, but a lot of then are in already. Except for pandoc-CSL, where that list is less complete; for this I've created #354.

**Comment by nickbart1980** [comment]
No, the second, newline-separated `csl-variable: content` format is not parsed out. This is with ‘pandoc CSL’ and BBT 1.4.6.

**Comment by retorquere** [comment]
It depends on the CSL variable. Which are you missing (please add on #354)

**Comment by nickbart1980** [comment]
Ah, I see, sorry. I tried `original-date`. WIll continue on https://github.com/ZotPlus/zotero-better-bibtex/issues/354.
