### ISSUE TITLE
Better BibTeX disabled after automatic Zotero update

### ISSUE THREAD

**Issue by samspo** [ZotPlus/zotero-better-bibtex#362]
Hi,

Better Bibtex is disabled with zotero 4.0.28.6

<img width="464" alt="capture d ecran 2015-09-28 a 14 09 53" src="https://cloud.githubusercontent.com/assets/1280210/10148829/a86c89a2-65ea-11e5-97cd-815e9863359f.png">

I'm on mac OS X 10.10.3
Is there anything I can do ?

Thnaks,

**Comment by retorquere** [comment]
There is supposed to be a message in that pane stating the reason for it being disabled, but as the other tabs are still visible, I think an error has occurred rather than that BBT has disabled itself. Could you please:

* go into the "Advanced" tab and tick "Enable after restart"
* restart Zotero
* go into the Advanced tab again
* click "View output"
* in the resulting window, select all text (cmd-a)
* paste the resulting log in a gist, or drop it in a text file in https://dbinbox.com/retorquere

What other extensions do you have installed? I've just tested on 4.0.28.6 with BBT 1.5.1, and I'm not seeing any problems.

**Comment by samspo** [comment]
Thank you. Just uploaded a file on https://dbinbox.com/retorquere

2015-09-28 14:31 GMT-07:00 retorquere <notifications@github.com>:

**Comment by retorquere** [comment]
Something is indeed interfering with BBT, but the log doesn't say which. Could you disable all your Firefox plugins except Zotero and BBT, and see if BBT starts up normally then? If so, could you start enabling plugins (with a restart after each) to see which triggers it?

**Comment by samspo** [comment]
Seems to work again. Even after I enabled all the plugins. Don't know what was going on.

Thank you very much and sorry to have bothered you.

**Comment by retorquere** [comment]
Never a problem, please don' apologise.
