### ISSUE TITLE
Access item key in postscript

### ISSUE THREAD

**Issue by pooranis** [ZotPlus/zotero-better-bibtex#404]
In the "postscript" option, is there any way to access the item key field?  I don't mean the citekey but the Zotero item key.  Other translators are able to access this field  (like https://github.com/zotero/translators/blob/master/CSV.js or  http://cangjie.info/blog/?p=386), but I can't seem to get it to work with BBT.

Thanks.

**Comment by retorquere** [comment]
That's probably because BBT is one of the few translators that uses the non-legacy exporter infrastructure; most translators (including those bundled with Zotero) use legacy mode, which is (I think) simpler to use, but some internals that I need don't work with it anymore, so I had to move over. Confusingly, the `BetterBibTeX JSON` exporter *does* use the legacy format since it uses other internals that aren't compatible with non-legacy objects, so exporting using BetterBibTeX JSON (which used to be the easiest way to get an exact copy of the internal state of exported references) won't help you much.

The key you want can be parsed out of `this.item.uri`; the uri is structured as `http://zotero.org/users/<library ID>/items/<item key>`, so in principle `this.item.uri.replace(/.*\//, '')` ought to do the job.

**Comment by retorquere** [comment]
(to be clear, it looks like in non-legacy mode translators are not handed the key; you're right it isn't available, but I don't remove it. There's very little I can do about this.)

**Comment by pooranis** [comment]
Parsing the uri is a viable solution. Thanks so much for the prompt reply! BBT
is such a useful plugin.

On Mon, Nov 23, 2015 at 4:59 AM, retorquere < notifications@github.com [notifications@github.com] > wrote:
(to be clear, it looks like in non-legacy mode translators are not handed the
key; you're right it isn't available, but I don't remove it. There's very little
I can do about this.)

—
Reply to this email directly or view it on GitHub
[https://github.com/ZotPlus/zotero-better-bibtex/issues/404#issuecomment-158891990] .[https://github.com/notifications/beacon/AEKmQ2lBpSb5ZiU7-Bld4dRyzGC3sLSjks5pItr_gaJpZM4GnNva.gif]

**Comment by retorquere** [comment]
Glad to be of help. If your question is answered to your satisfaction, would you mind if I close the issue?

**Comment by pooranis** [comment]
Yes, of course.
