### ISSUE TITLE
Condense filter not replacing spaces as specified

### ISSUE THREAD

**Issue by mdlincoln** [ZotPlus/zotero-better-bibtex#427]
Possibly #308 rearing its head again?

My citation key format is set to:

```
[auth:lower:condense,_][year][0]
```

After a recent update, `condense,_` appears to be simply removing spaces, not replacing them with `_`. For example, an entry with `de Piles, Roger` in the Zotero author field is formatted as `depiles1708` instead of `de_piles1708` (which is the citekey that it had originally generated for me)

**Comment by retorquere** [comment]
"auth" follows the JabRef convention so it has space-removal pre-applied (see https://zotplus.github.io/better-bibtex/citation-keys.html#filters, "usage notes"). I think if you use `Auth` instead of `auth` it will do what you want. `Auth` determines the authornames as Jebref does but does no further cleaning; `auth` takes the output of `Auth`, applies diacritics folding, and removes anything that is not alphanumeric, and is not in the set `-_!$*+./;?[]`, so by the time `condense` is applied there are no spaces to act on.

**Comment by retorquere** [comment]
There was at some time a bug where `auth` did not apply the cleaning, which is probably the behavior you still have in mind. Sorry for the disruption that caused.

**Comment by retorquere** [comment]
I've updated the docs, this really wasn't clear.

**Comment by mdlincoln** [comment]
Thanks for the quick response! Using `Auth` fixes the problem.

**Comment by retorquere** [comment]
Thank you for your understanding.
