### ISSUE TITLE
Issue citing website

### ISSUE THREAD

**Issue by pierrebenz** [ZotPlus/zotero-better-bibtex#430]
I seem to be having issues citing a website with Better-bibtex. At the moment a web page is saved with Zotero and better-bibtex as a misc{} with the fields title, timestamp, urldate, how published etc. However, that leaves the citation field empty with only the title field showing anything (no timestamp, url or url accessed date).

The only format that seems to work is online{} with fields urldate & url, however, I need to edit the *.bib manually to get it that way. 

Is this a common problem? How else do you specify these flags?

**Comment by retorquere** [comment]
Since bibtex doesn't natively support urls BBT doesn't export them by default, although now that you say it it makes sense to export a compatible version specifically for website references. I'll get to that this afternoon, but for now you can enable it in the BBT preferences. 

But if you want @online entries, you will want to use Better BibLaTeX rather than Better BibTeX. Bibtex doesn't support the @online reference type, which is why I picked @misc

**Comment by pierrebenz** [comment]
Thanks for the quick reply. Yes, changing to BBL fixed the issue for me.

**Comment by doctornerdis** [comment]
This may be a problem for only for me because I use the Chicago author-date CSL, but I've found an issue when dealing with websites, too. I think BBL should transfer the **Website Title** in Zotero to the **Journal** or **Journaltitle** fields, not the **Titleaddon** field. 

Right now, if I have the following entry in Zotero:

<img width="335" alt="screen shot 2016-05-10 at 1 09 47 pm" src="https://cloud.githubusercontent.com/assets/16094430/15143067/8d9aaf92-16b0-11e6-94c7-a53198dad4a4.png">

It comes out as:

```
@online{snoj_population_2013,
	Author = {Snoj, Jure},
	Date = {2013-12-18},
	Langid = {english},
	Timestamp = {2016-02-01T06:48:54Z},
	Title = {Population of {{Qatar}} by {{Nationality}}},
	Titleaddon = {BQ Magazine},
	Url = {http://www.bq-magazine.com/economy/2013/12/population-qatar},
	Urldate = {2016-02-01}}
```

Which renders incorrectly as:

<img width="460" alt="screen shot 2016-05-10 at 1 17 14 pm" src="https://cloud.githubusercontent.com/assets/16094430/15143282/8d5e735a-16b1-11e6-9d95-57cd170df6ac.png">

But when you have 

```tex
@online{snoj_population_2013,
	Author = {Snoj, Jure},
	Date = {2013-12-18},
	Journal = {BQ Magazine},
	Langid = {english},
	Timestamp = {2016-02-01T06:48:54Z},
	Title = {Population of {{Qatar}} by {{Nationality}}},
	Url = {http://www.bq-magazine.com/economy/2013/12/population-qatar},
	Urldate = {2016-02-01}}
```

It renders correctly as:

<img width="463" alt="screen shot 2016-05-10 at 1 18 38 pm" src="https://cloud.githubusercontent.com/assets/16094430/15143336/cc05beec-16b1-11e6-833a-6dcd60784e2b.png">
