### ISSUE TITLE
Auto-export always recursive regardless of options

### ISSUE THREAD

**Issue by xenocrates87** [ZotPlus/zotero-better-bibtex#450]
When setting up BibLaTeX auto-export for nested collections, the exported parent collection always contains all items of nested collections. I have tried ticking and unticking "Export collections recursively" and it makes zero difference on the output bib-file. I have it output for Better BibLaTeX, UTF-8 no auto-abbreviate and no note exporting.

I have made an error report with following report ID: ZSZB2E43

**Comment by retorquere** [comment]
So it does... thinking about how to proceed on this one.

To explain what's going on, in the past, Zotero exported whatever you saw in the UI; if you displayed recursively, it had the side effect of recursive exports, and if you didn't display recursively, you also wouldn't get that side effect. But pretty much no one knows (or uses) this, as it's [not an exposed option](https://forums.zotero.org/discussion/3317/recursive-display-of-all-items-of-a-collection-and-its-subcollections/) in Zotero; "show recursively" defaulted to "no", and there was no obvious way to change that.

BBT doesn't actually decide what to export when you toggle the option; I just added a checkbox to toggle the previously hidden option to display recursively on or off without having to go into `about:config`, relying on the side effect it had on exports. But since the side effect was never officially sanctioned behavior, and it didn't occur very often (for non-BBT users) because the toggle is not part of the Zotero UI, they're free to do as they want, all the way up to simply removing that (hidden) option should they want to. It looks like the side effect has disappeared somewhere since I implemented that toggle.

The question is then whether I should

1. emulate the old behavior by actively filtering out the non-root items. It's not something a translator is supposed to be capable of doing -- I'd have to subvert some internals to get it done -- and non-BBT translators would still export recursively always, so the export behavior would be inconsistent between BBT and other translators.
2. "simply" label the preference more honestly for what it does ("Display collections recursively") rather than for the side effect it had ("Export collections recursively"), or even
3. remove it entirely, as toggling the option to display recursively doesn't really relate to BBT functionality anymore.

As of yet undecided on what I'm going to do. How important is non-recursive export for you?

**Comment by xenocrates87** [comment]
Well, it's not a critical feature per se. I use the nested collections to help keep track of related, but separate collections. In the current situation, I have two bib-files for the same document, because I need one for my own publications and one for the end bibliography.

As it is now, I end up with duplicate entries in my end bibliography, but it might be that the problem only has temporary symptoms because of my usage of \nocite{*}. When I switch over to actually citing the specific entries, the problem will hopefully end up consisting merely of additional entries in my bib-file and not duplicate entries in the finished document.

**Comment by retorquere** [comment]
I've looked into this and the changes would be too fragile, sorry. I'm going to remove the option in the next release.
